### ISSUE TITLE
在吗？报错

### ISSUE THREAD

**Issue by Losketch** [luzhixing12345/image-FFT#1]
系统：Windows 10 22H2
python版本：3.12.0
opencv-python	：4.9.0.80
pyqt5		：5.15.2
numpy		：1.26.4
pygame		：2.5.2

所有图片到了 `生成结果` 这一步都是这种报错，测试图片：
![123](https://github.com/luzhixing12345/image-FFT/assets/140333245/5511299e-553b-46cd-a07c-b8d71fcde51e)

```
PS D:\unicode\image-FFT\image-FFT-main> & C:/Users/76227/AppData/Local/Programs/Python/Python312/python.exe d:/unicode/image-FFT/image-FFT-main/GUI.py
pygame 2.5.2 (SDL 2.28.3, Python 3.12.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
libpng warning: bKGD: invalid
libpng warning: bKGD: invalid
libpng warning: bKGD: invalid
./images/123.txt has been successfully created by ./images/123.svg
Traceback (most recent call last):
  File "d:\unicode\image-FFT\image-FFT-main\GUI.py", line 96, in fftImageProcess
    draw(fileName)
  File "d:\unicode\image-FFT\image-FFT-main\fft.py", line 58, in draw
    PP = fftProcess(fname)
         ^^^^^^^^^^^^^^^^^
  File "d:\unicode\image-FFT\image-FFT-main\fft.py", line 18, in fftProcess
    pointList.append((float(pointAll[i+1]),float(pointAll[i])))
                            ~~~~~~~~^^^^^
IndexError: list index out of range
```

**Comment by luzhixing12345** [comment]
应该是在处理svg格式的时候没有考虑多个封闭图像的问题，稍晚修改一下

**Comment by Losketch** [comment]
请教一下
part2: manim（不须）
这里看的是一脸懵逼，能不能详细说明一下怎么输出MP4

还有怎么调整线条粗细（黄色的那个）

**Comment by luzhixing12345** [comment]
之前的报错问题解决了，但本身这个程序一开始的想法是对于一个物体边缘轮廓的绘制，所以对于内部的线条添加了一些过滤器，对于你的输入案例来说如果想要充分保留字体的所有边缘部分可以去掉高斯滤波然后调整 canny 的阈值以得到内部完整线条

https://github.com/luzhixing12345/image-FFT/blob/f3312b14210a8b932c08031825f15beaa58fc455/SVG.py#L38-L42
